// Please read README for specs before adding :D

module.exports = [
	{
		name: 'Chester Lynn',
		website: 'https://github.com/halchester',
		github: 'halchester',
		emoji: '😋',
		info:
			'Passionate about React ecosystem and loves Javascript. Front-end developer with very little css knowledge :P and loves cycling!',
		phone: 'iphone',
		laptop: 'mac',
		tags: [
			'Python',
			'Django',
			'Javascript',
			'Typescript',
			'React',
      'Next',
      'Tailwindcss',
			'Redux',
			'Express',
			'MongoDB',
			'firebase',
			'git',
		],
	},
	{
		name: 'Hein Thant Maung Maung',
		website: 'https://heinthanth.ninja',
		github: 'heinthanth',
		emoji: '😴',
		info:
			'FullStack Web, Mobile developer, a junior DevOps, creator of UiT lang and a PHP fan',
		phone: 'iphone',
		laptop: 'mac',
		tags: [
			'PHP',
			'JavaScript',
			'C++',
			'UiT Lang',
			'React',
			'Flutter',
			'Laravel',
			'Express',
			'Java',
			'Python',
			'Linux',
			'Docker',
		],
	},
	{
		name: 'Min Thu Kyaw',
		website: 'https://minthukyaw.bike',
		github: 'thukyaw11',
		emoji: '👳🏽‍♂️',
		info: 'A passionate Javascriprter with VUE js, Backend Developer and Biker',
		phone: 'android',
		laptop: 'linux',
		tags: [
			'Javascript',
			'VUE',
			'React JS',
			'Dart',
			'Flutter',
			'PHP',
			'Laravel',
			'Linux',
			'C++',
			'Firebase',
			'git',
		],
	},
];
