module.exports = [
  {
    name: "Htoo Aung Lynn",
    website: "https://halchester.netlify.app",
    github: "halchester",
    emoji: "😋",
    info:
      "React and Django developer, interested in bikes and an undergrad from MIIT",
    phone: "iphone",
    laptop: "mac",
    tags: [
      "Python",
      "Javascript",
      "Django",
      "React",
      "Flutter",
      "openCV",
      "TensorFlow",
    ],
  },
  {
    name: "John Doe",
    website: "halchester.netlify.app",
    github: "johndoe",
    emoji: "😋",
    info: "A randome Dude",
    phone: "andriod",
    laptop: "mac",
    tags: [
      "Python",
      "Javascript",
      "Django",
      "React",
      "Flutter",
      "openCV",
      "mongoDB",
    ],
  },
  {
    name: "Jane Doe",
    website: "janedoe.netlify.app",
    github: "janedoe",
    emoji: "!!!",
    info: "Mrs.Doe",
    phone: "iphone",
    laptop: "linux",
    tags: [
      "Python",
      "Javascript",
      "Django",
      "React",
      "Flutter",
      "openCV",
      "mongoDB",
    ],
  },
];
