module.exports = [
  {
    name: "Htoo Aung Lynn",
    website: "https://halchester.netlify.app",
    github: "halchester",
    emoji: "😋",
    info:
      "React and Django developer, interested in bikes and an undergrad from MIIT",
    phone: "iphone",
    laptop: "mac",
    tags: [
      "Python",
      "Javascript",
      "Django",
      "React",
      "Flutter",
      "openCV",
      "TensorFlow",
      "firebase",
      "git",
    ],
  },
  {
    name: "Hein Thant Maung Maung",
    website: "https://heinthanth.ninja",
    github: "heinthanth",
    emoji: "😴",
    info:
      "FullStack Web, Mobile developer, a junior DevOps, creator of UiT lang and a PHP fan",
    phone: "iphone",
    laptop: "mac",
    tags: [
      "PHP",
      "JavaScript",
      "C++",
      "UiT Lang",
      "React",
      "Flutter",
      "Laravel",
      "Express",
      "Java",
      "Python",
      "Linux",
      "Docker",
    ],
  },
  {
    name: "Min Thu Kyaw",
    website: "https://minthukyaw.bike",
    github: "thukyaw11",
    emoji: "👳🏽‍♂️",
    info: "A passionate Javascriprter with VUE js, Backend Developer and Biker",
    phone: "android",
    laptop: "linux",
    tags: [
      "Javascript",
      "VUE",
      "React JS",
      "Dart",
      "Flutter",
      "PHP",
      "Laravel",
      "Linux",
      "C++",
      "Firebase",
      "git",
    ],
  },
];
